# Generated by Django 3.2.6 on 2021-09-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
