# Generated by Django 3.2.6 on 2021-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_following_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
